// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoKTwCrR_x9zqfrLD8EzAUq1QSuZhrYUA',
    appId: '1:510785169210:web:070482646b439db49f5203',
    messagingSenderId: '510785169210',
    projectId: 'danceconnect-bf8c3',
    authDomain: 'danceconnect-bf8c3.firebaseapp.com',
    storageBucket: 'danceconnect-bf8c3.appspot.com',
    measurementId: 'G-9YXBLBHZNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChZfdOlnZDJ6_aXuC6PAFV3ATmVvPloIE',
    appId: '1:510785169210:android:15f239b6cb7e6d4f9f5203',
    messagingSenderId: '510785169210',
    projectId: 'danceconnect-bf8c3',
    storageBucket: 'danceconnect-bf8c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaMUmA9rKPazM7tBeEEelzUuonq4hrxUk',
    appId: '1:510785169210:ios:ccd782bd1c13a5799f5203',
    messagingSenderId: '510785169210',
    projectId: 'danceconnect-bf8c3',
    storageBucket: 'danceconnect-bf8c3.appspot.com',
    androidClientId: '510785169210-malpko25hmvn87ojg9v25iifuqsbanm0.apps.googleusercontent.com',
    iosClientId: '510785169210-hhdgrpu4gn90rijha0mnrssu6ap4d5u7.apps.googleusercontent.com',
    iosBundleId: 'com.example.danceConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaMUmA9rKPazM7tBeEEelzUuonq4hrxUk',
    appId: '1:510785169210:ios:268d1e3b9f9946b19f5203',
    messagingSenderId: '510785169210',
    projectId: 'danceconnect-bf8c3',
    storageBucket: 'danceconnect-bf8c3.appspot.com',
    androidClientId: '510785169210-malpko25hmvn87ojg9v25iifuqsbanm0.apps.googleusercontent.com',
    iosClientId: '510785169210-19sv7n72asil7sqo4ijqgosuhb2vog4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.danceConnect.RunnerTests',
  );
}
